license:
  name: lgpl
  version: 3
program:
  name: Formula-Analysis-Sat4J Lib
  description: Library to analyze propositional formulas with Sat4J.
  authors: Sebastian Krieter
  url: https://github.com/skrieter/formula-analysis-sat4j
  year: 2021
